export const currency = "ر.س";

export const categories = [
  { id: "personal-finance", name: "التمويل الشخصي والادخار", icon: "💰" },
  { id: "investment", name: "الاستثمار والأسواق المالية", icon: "📈" },
  { id: "real-estate", name: "العقارات", icon: "🏠" },
  { id: "business", name: "الأعمال والشركات", icon: "🏢" },
  { id: "specialized", name: "قطاعات متخصصة", icon: "⚙️" },
  { id: "life-events", name: "الحياة والمناسبات", icon: "🌙" },
];

export const products = [
  // ─── الفئة 1: التمويل الشخصي والادخار ───────────────────────────────
  {
    id: "personal-budget-planner",
    name: "مخطط الميزانية والادخار الشخصي",
    category: "personal-finance",
    price: 49,
    originalPrice: 99,
    description:
      "تحكّم في أموالك الشخصية من مكان واحد. سجّل دخلك ومصاريفك، تابع أهداف ادخارك، واحسب صافي ثروتك بدقة — كل ذلك بالعربية وبتصميم سهل.",
    longDescription:
      "لماذا تختفي فلوسك كل شهر؟ مخطط الميزانية الشخصية يساعدك على تتبع كل ريال، حساب صافي ثروتك الحقيقية، ووضع أهداف ادخار واضحة. 7 من كل 10 أشخاص بدون ميزانية — لا تكن منهم.",
    features: [
      "الميزانية الشهرية",
      "المتابعة السنوية برسم بياني",
      "أهداف الادخار",
      "حاسبة صافي الثروة",
    ],
    icon: "💰",
    image: null,
    badge: "الأكثر مبيعاً",
    badgeColor: "emerald",
    rating: 4.9,
    reviews: 312,
    audience: "الأفراد والعائلات",
    compatible: "Excel 2016, 2019, 2021, Microsoft 365",
  },
  {
    id: "retirement-fire-planner",
    name: "مخطط التقاعد والاستقلال المالي",
    category: "personal-finance",
    price: 79,
    originalPrice: null,
    description:
      "اعرف بالضبط متى تستطيع التقاعد وكم تحتاج. حاسبة مبنية على قاعدة الـ4% العالمية مع محاكاة 30 سنة لثروتك.",
    longDescription:
      "هل تعرف متى ستتقاعد؟ هذه الأداة تحسب لك بدقة متى تحقق الاستقلال المالي، مع 3 سيناريوهات للمحاكاة على 30 سنة. تشمل حاسبة FIRE الكاملة وتخطيط مصاريف التقاعد وزكاة المدخرات.",
    features: [
      "حاسبة FIRE (قاعدة الـ4%)",
      "محاكاة 30 سنة (3 سيناريوهات)",
      "تخطيط مصاريف التقاعد",
      "حاسبة زكاة المدخرات",
    ],
    icon: "🏖️",
    image: null,
    badge: null,
    badgeColor: null,
    rating: 4.8,
    reviews: 147,
    audience: "المدخرون والمخططون للمستقبل",
    compatible: "Excel 2016, 2019, 2021, Microsoft 365",
  },
  {
    id: "debt-repayment-planner",
    name: "مخطط الديون وخطة السداد المتسارع",
    category: "personal-finance",
    price: 49,
    originalPrice: null,
    description:
      "تخلّص من ديونك بأسرع وقت وأقل تكلفة. قارن بين استراتيجيتي 'كرة الثلج' و'الانهيار الجليدي' واعرف كم ستوفّر.",
    longDescription:
      "الديون ثقيلة — لكن الخطة الصحيحة تفرق كثيراً. قارن بين استراتيجية كرة الثلج (من الأصغر) والانهيار الجليدي (من الأعلى فائدة)، وشاهد جدول السداد لـ36 شهراً مع لوحة تقدم واضحة.",
    features: [
      "جرد الديون الكامل",
      "استراتيجية الانهيار الجليدي",
      "استراتيجية كرة الثلج",
      "جدول سداد 36 شهراً",
      "لوحة تقدم مرئية",
    ],
    icon: "🔓",
    image: null,
    badge: null,
    badgeColor: null,
    rating: 4.7,
    reviews: 98,
    audience: "المثقلون بالديون والساعون للتحرر المالي",
    compatible: "Excel 2016, 2019, 2021, Microsoft 365",
  },
  {
    id: "insurance-protection",
    name: "حاسبة التأمين والحماية المالية",
    category: "personal-finance",
    price: 49,
    originalPrice: null,
    description:
      "احمِ نفسك وعائلتك وأعمالك. اعرف حجم التغطية التأمينية التي تحتاجها فعلاً وأين توجد الفجوات.",
    longDescription:
      "معظم الناس يدفعون تأميناً لا يناسبهم أو يفتقدون تغطية حيوية. هذه الأداة تحسب لك التغطية المثلى لتأمين الحياة، الصحة، وأعمالك — مع تحليل فجوة التغطية الحالية.",
    features: [
      "تأمين الحياة",
      "مقارنة التأمين الصحي",
      "صندوق الطوارئ",
      "تأمين الأعمال",
      "تحليل فجوة التغطية",
    ],
    icon: "🛡️",
    image: null,
    badge: null,
    badgeColor: null,
    rating: 4.6,
    reviews: 73,
    audience: "الأفراد وأصحاب الأعمال",
    compatible: "Excel 2016, 2019, 2021, Microsoft 365",
  },
  {
    id: "loan-bank-comparison",
    name: "حاسبة القروض والتمويل ومقارنة البنوك",
    category: "personal-finance",
    price: 49,
    originalPrice: 99,
    description:
      "قبل أن توقّع أي تمويل، اعرف التكلفة الحقيقية. قارن عروض 6 بنوك بمعدل APR الحقيقي — فرق قد يصل لـ 18,400 ريال.",
    longDescription:
      "نفس المبلغ. نفس المدة. فرق يصل لـ 18 ألف ريال. معظم الناس يختارون البنك بناءً على الأقرب من البيت، لا APR الحقيقي. هذه الأداة تبيّن لك الفرق بالأرقام عبر مقارنة شاملة لـ6 بنوك.",
    features: [
      "مقارنة 6 بنوك بـ APR الحقيقي",
      "حاسبة التمويل الشخصي ونسبة الاستقطاع",
      "تمويل السيارة (مرابحة / إيجار)",
      "حاسبة السداد المبكر",
      "جدول الأقساط التفصيلي",
    ],
    icon: "🏦",
    image: null,
    badge: "الأكثر مبيعاً",
    badgeColor: "emerald",
    rating: 4.9,
    reviews: 256,
    audience: "الباحثون عن تمويل شخصي أو سيارة",
    compatible: "Excel 2016, 2019, 2021, Microsoft 365",
  },

  // ─── الفئة 2: الاستثمار والأسواق المالية ────────────────────────────
  {
    id: "investment-portfolio",
    name: "محفظة الاستثمار الشاملة",
    category: "investment",
    price: 99,
    originalPrice: 179,
    description:
      "تتبّع كل استثماراتك في مكان واحد — أسهم، عقارات، ذهب، وودائع. اعرف عائدك الحقيقي وتوزيع أصولك.",
    longDescription:
      "أداة شاملة لإدارة محفظتك الاستثمارية بالكامل. تتبّع أسهمك في تداول، عقاراتك، ذهبك وودائعك في لوحة واحدة مع رسم دائري لتوزيع الأصول وحاسبة FIRE متكاملة.",
    features: [
      "محفظة الأسهم (تداول)",
      "تتبع العقارات",
      "الذهب والودائع",
      "ملخص المحفظة برسم دائري",
      "حاسبة FIRE",
    ],
    icon: "📊",
    image: null,
    badge: "مميز",
    badgeColor: "amber",
    rating: 4.9,
    reviews: 189,
    audience: "المستثمرون الأفراد",
    compatible: "Excel 2016, 2019, 2021, Microsoft 365",
  },
  {
    id: "tadawul-stocks-analysis",
    name: "أدوات تحليل أسهم تداول",
    category: "investment",
    price: 129,
    originalPrice: 199,
    description:
      "اتخذ قرارات استثمار مدروسة في سوق تداول. فارز أسهم بنظام تقييم تلقائي، تحليل أساسي، وفحص شرعي للأسهم.",
    longDescription:
      "الأداة الأشمل لمستثمر سوق تداول السعودي. فارز أسهم بنظام تقييم تلقائي، تحليل أساسي كامل (P/E, P/B, DCF)، فحص شرعي وفق معايير AAOIFI، مقارنة القطاعات، ومتابعة المحفظة.",
    features: [
      "فارز الأسهم بتقييم تلقائي",
      "التحليل الأساسي (P/E, P/B, DCF)",
      "الفحص الشرعي (AAOIFI)",
      "مقارنة القطاعات",
      "متابعة المحفظة",
    ],
    icon: "📉",
    image: null,
    badge: "حزمة مميزة",
    badgeColor: "amber",
    rating: 5.0,
    reviews: 134,
    audience: "المستثمرون في السوق السعودي",
    compatible: "Excel 2016, 2019, 2021, Microsoft 365",
  },

  // ─── الفئة 3: العقارات ───────────────────────────────────────────────
  {
    id: "real-estate-analysis",
    name: "حاسبة تحليل العقارات والاستثمار العقاري",
    category: "real-estate",
    price: 99,
    originalPrice: 169,
    description:
      "قرارات عقارية مبنية على أرقام. هل تشتري أم تستأجر؟ ما عائد العقار الاستثماري؟ أي بنك يقدّم أفضل تمويل؟",
    longDescription:
      "الأداة الكاملة لكل قرار عقاري في السعودية. تحليل الشراء مقابل الإيجار بالأرقام الحقيقية، تقييم العقار الاستثماري (NOI / Cap Rate / DSCR)، مقارنة عروض البنوك، وجدول سداد 20 سنة.",
    features: [
      "شراء أم إيجار؟ (مقارنة حقيقية)",
      "تحليل العقار الاستثماري (NOI / Cap Rate / DSCR)",
      "مقارنة عروض البنوك",
      "جدول سداد 20 سنة",
      "جدوى التطوير العقاري",
      "معايير السوق السعودي",
    ],
    icon: "🏠",
    image: null,
    badge: "الأكثر طلباً",
    badgeColor: "violet",
    rating: 4.8,
    reviews: 167,
    audience: "المستثمرون العقاريون والمشترون الجدد",
    compatible: "Excel 2016, 2019, 2021, Microsoft 365",
  },
  {
    id: "rental-property-management",
    name: "أدوات إدارة العقارات المؤجرة",
    category: "real-estate",
    price: 79,
    originalPrice: null,
    description:
      "للملّاك — أدِر عقاراتك بكفاءة. تتبّع المستأجرين، حصّل الإيجارات، راقب الصيانة، واحسب عائد كل عقار.",
    longDescription:
      "إذا كنت تمتلك عقاراً أو أكثر للإيجار، هذه الأداة تنظم كل شيء في مكان واحد: بيانات المستأجرين، سجل تحصيل الإيجارات، طلبات الصيانة، وتحليل العائد لكل عقار في محفظتك.",
    features: [
      "محفظة العقارات",
      "سجل المستأجرين",
      "تحصيل الإيجارات",
      "سجل الصيانة",
      "تحليل العائد لكل عقار",
    ],
    icon: "🔑",
    image: null,
    badge: null,
    badgeColor: null,
    rating: 4.7,
    reviews: 89,
    audience: "ملّاك العقارات المؤجرة",
    compatible: "Excel 2016, 2019, 2021, Microsoft 365",
  },

  // ─── الفئة 4: الأعمال والشركات ──────────────────────────────────────
  {
    id: "profit-loss-cashflow",
    name: "نموذج الأرباح والخسائر والتدفق النقدي",
    category: "business",
    price: 99,
    originalPrice: 169,
    description:
      "نموذج مالي شامل للشركات الصغيرة والمتوسطة. تابع إيراداتك وأرباحك وتدفقك النقدي، واعرف نقطة التعادل.",
    longDescription:
      "النموذج المالي الأساسي لكل شركة صغيرة أو متوسطة. قائمة دخل (P&L) شهرية وسنوية، تحليل التدفق النقدي، نقطة التعادل مع جدول حساسية، ومؤشرات الأداء الرئيسية (KPIs).",
    features: [
      "قائمة الدخل الشهرية والسنوية (P&L)",
      "تحليل التدفق النقدي",
      "نقطة التعادل مع جدول حساسية",
      "مؤشرات الأداء KPIs",
    ],
    icon: "📋",
    image: null,
    badge: "الأكثر مبيعاً",
    badgeColor: "emerald",
    rating: 4.8,
    reviews: 201,
    audience: "أصحاب الشركات الصغيرة والمتوسطة",
    compatible: "Excel 2016, 2019, 2021, Microsoft 365",
  },
  {
    id: "business-docs-bundle",
    name: "حزمة قوالب وثائق الأعمال الاحترافية",
    category: "business",
    price: 149,
    originalPrice: 249,
    description:
      "كل ما تحتاجه لتأسيس وإدارة مشروعك. خطة عمل، دراسة جدوى، نماذج موارد بشرية، وعقد عمل متوافق مع نظام العمل السعودي.",
    longDescription:
      "الحزمة الأشمل لتأسيس وإدارة مشروعك في السعودية. تشمل قالب خطة العمل، دراسة الجدوى، نماذج الموارد البشرية، عقد العمل المتوافق مع نظام العمل السعودي، لوحة KPIs، والخطة التشغيلية.",
    features: [
      "قالب خطة العمل",
      "دراسة الجدوى",
      "نماذج الموارد البشرية",
      "عقد العمل (متوافق مع نظام العمل)",
      "لوحة KPIs",
      "الخطة التشغيلية",
    ],
    icon: "📁",
    image: null,
    badge: "حزمة مميزة",
    badgeColor: "amber",
    rating: 4.9,
    reviews: 178,
    audience: "المؤسسون والمدراء",
    compatible: "Excel 2016, 2019, 2021, Microsoft 365",
  },
  {
    id: "startup-planning-bundle",
    name: "حزمة أدوات تخطيط المشاريع الناشئة",
    category: "business",
    price: 149,
    originalPrice: 229,
    description:
      "من الفكرة إلى الإطلاق. تحقّق من فكرتك، خطط طريقك، واحسب اقتصاديات وحدتك (Unit Economics) قبل أن تستثمر.",
    longDescription:
      "قبل أن تستثمر ريالاً واحداً، تحقّق من فكرتك. الحزمة تشمل مصفوفة التحقق من الفكرة، خارطة طريق 12 شهراً، Unit Economics (CAC/LTV)، نموذج التمويل، وOKRs وKPIs. كل ما يحتاجه رائد الأعمال.",
    features: [
      "مصفوفة التحقق من الفكرة",
      "خارطة طريق 12 شهراً",
      "Unit Economics (CAC / LTV)",
      "نموذج التمويل",
      "OKRs وKPIs",
    ],
    icon: "🚀",
    image: null,
    badge: "حزمة مميزة",
    badgeColor: "amber",
    rating: 4.8,
    reviews: 112,
    audience: "رواد الأعمال والمؤسسون",
    compatible: "Excel 2016, 2019, 2021, Microsoft 365",
  },
  {
    id: "product-pricing-analysis",
    name: "أدوات تحليل وتسعير المنتجات والخدمات",
    category: "business",
    price: 79,
    originalPrice: null,
    description:
      "سعّر بثقة ولا تبع بخسارة أبداً. احسب هامشك الحقيقي، قارن منافسيك، وحدّد السعر الأمثل لمنتجاتك.",
    longDescription:
      "التسعير الخاطئ يقتل الأعمال. هذه الأداة تحسب لك التكلفة الحقيقية، هامش الربح الفعلي، وتقارن أسعارك بالمنافسين. تدعم تسعير التكلفة+، تسعير القيمة، وتسعير الحزم.",
    features: [
      "تسعير التكلفة+",
      "تسعير القيمة",
      "تحليل الهوامش",
      "مقارنة المنافسين",
      "تسعير الحزم",
    ],
    icon: "🏷️",
    image: null,
    badge: null,
    badgeColor: null,
    rating: 4.7,
    reviews: 94,
    audience: "التجار وأصحاب الخدمات",
    compatible: "Excel 2016, 2019, 2021, Microsoft 365",
  },
  {
    id: "vat-tax-planning",
    name: "أدوات التخطيط الضريبي وضريبة القيمة المضافة",
    category: "business",
    price: 79,
    originalPrice: null,
    description:
      "احسب ضريبتك بدقة وتجنّب غرامات زاتكا. حاسبة VAT، سجل فواتير، إقرار ربعي جاهز، وتقويم الالتزامات.",
    longDescription:
      "الامتثال الضريبي أصبح إلزامياً. هذه الأداة تحسب VAT تلقائياً، تحتفظ بسجل فواتيرك، وتُعدّ الإقرار الضريبي الربعي مع تقويم كامل لالتزامات زاتكا.",
    features: [
      "حاسبة VAT (15%)",
      "سجل الفواتير",
      "الإقرار الضريبي الربعي",
      "زكاة الشركات",
      "تقويم الامتثال (ZATCA)",
    ],
    icon: "🧾",
    image: null,
    badge: "جديد",
    badgeColor: "blue",
    rating: 4.8,
    reviews: 143,
    audience: "المنشآت والمحاسبون",
    compatible: "Excel 2016, 2019, 2021, Microsoft 365",
  },
  {
    id: "freelancer-tools",
    name: "أدوات الفريلانسر والعمل الحر",
    category: "business",
    price: 49,
    originalPrice: null,
    description:
      "احسب سعر ساعتك الحقيقي، تتبّع مشاريعك، وأدِر دخلك بذكاء. مصمّمة لمن يعمل لحسابه الخاص.",
    longDescription:
      "العمل الحر يتطلب إدارة مالية أكثر انضباطاً. هذه الأداة تحسب سعر ساعتك بناءً على أهدافك المالية، تتابع مشاريعك وعملاءك، وتُعدّ تقرير الدخل والمصاريف الشهري.",
    features: [
      "حاسبة سعر الساعة الحقيقي",
      "متابعة المشاريع",
      "الدخل والمصاريف (P&L)",
      "تحليل العملاء",
      "خطة الدخل السنوي",
    ],
    icon: "💻",
    image: null,
    badge: null,
    badgeColor: null,
    rating: 4.7,
    reviews: 118,
    audience: "المستقلون والعاملون بالعمل الحر",
    compatible: "Excel 2016, 2019, 2021, Microsoft 365",
  },

  // ─── الفئة 5: قطاعات متخصصة ─────────────────────────────────────────
  {
    id: "engineering-project-bundle",
    name: "حزمة قوالب الهندسة وإدارة المشاريع",
    category: "specialized",
    price: 149,
    originalPrice: 229,
    description:
      "أدوات احترافية للمهندسين ومديري المشاريع. جدول كميات، مخطط جانت، فحص جودة، وضبط تكاليف.",
    longDescription:
      "الحزمة الكاملة لإدارة المشاريع الهندسية. تشمل جدول الكميات (BOQ)، مخطط جانت، قائمة فحص الجودة، ضبط تكاليف المشروع، سجل المخاطر، وتقرير التقدم الأسبوعي.",
    features: [
      "جدول الكميات (BOQ)",
      "مخطط جانت",
      "قائمة فحص الجودة",
      "ضبط تكاليف المشروع",
      "سجل المخاطر",
      "تقرير التقدم",
    ],
    icon: "⚙️",
    image: null,
    badge: "حزمة مميزة",
    badgeColor: "amber",
    rating: 4.8,
    reviews: 97,
    audience: "المهندسون ومديرو المشاريع",
    compatible: "Excel 2016, 2019, 2021, Microsoft 365",
  },
  {
    id: "ecommerce-analytics",
    name: "أدوات تحليل التجارة الإلكترونية والمتجر",
    category: "specialized",
    price: 79,
    originalPrice: null,
    description:
      "أي منتج يحقق 80% من ربحك؟ تحليل ABC يكشف المنتجات الذهبية — وتحليل RFM يبيّن من هم عملاؤك الحقيقيون.",
    longDescription:
      "أداة متكاملة لأصحاب المتاجر الإلكترونية. اكتشف المنتجات التي تحقق أكبر ربح بتحليل ABC، تعرّف على عملاءك الأكثر قيمة بتحليل RFM، أدر مخزونك، وضع خطة نمو مبنية على بيانات حقيقية.",
    features: [
      "لوحة KPIs للمتجر",
      "تحليل المنتجات (ABC)",
      "تحليل العملاء (RFM)",
      "إدارة المخزون",
      "خطة النمو",
    ],
    icon: "🛒",
    image: null,
    badge: "الأكثر طلباً",
    badgeColor: "violet",
    rating: 4.8,
    reviews: 134,
    audience: "أصحاب المتاجر الإلكترونية",
    compatible: "Excel 2016, 2019, 2021, Microsoft 365",
  },
  {
    id: "restaurant-management",
    name: "أدوات تخطيط وإدارة المطعم والمقهى",
    category: "specialized",
    price: 79,
    originalPrice: 149,
    description:
      "يشتغل كثير ويربح قليل؟ المشكلة في الأرقام. احسب Food Cost لكل طبق، هامش ربحك، ونقطة تعادلك بدقة.",
    longDescription:
      "صاحب المطعم قبل الأداة: يسعّر بالحدس، ما يعرف food cost، يشتغل كثير يربح قليل. بعد الأداة: food cost لكل طبق، هامش ربح واضح، نقطة تعادل محسوبة، جدول ورديات منظم.",
    features: [
      "تسعير قائمة الطعام",
      "تكلفة الوصفات (Food Cost)",
      "المبيعات اليومية",
      "نقطة التعادل",
      "جدول الورديات",
    ],
    icon: "🍽️",
    image: null,
    badge: "الأكثر طلباً",
    badgeColor: "violet",
    rating: 4.9,
    reviews: 176,
    audience: "أصحاب المطاعم والمقاهي",
    compatible: "Excel 2016, 2019, 2021, Microsoft 365",
  },
  {
    id: "solar-energy-calculator",
    name: "حاسبة الطاقة الشمسية والتوفير في الكهرباء",
    category: "specialized",
    price: 49,
    originalPrice: null,
    description:
      "احسب عائدك من الطاقة الشمسية قبل أن تستثمر. حلّل استهلاكك، صمّم نظامك، واعرف فترة الاسترداد على 25 سنة.",
    longDescription:
      "قبل أن تستثمر في الطاقة الشمسية، اعرف الأرقام الحقيقية. هذه الأداة تحلل استهلاكك الكهربائي، تصمم النظام الشمسي المثالي لك، وتحسب العائد على مدى 25 سنة مع تدقيق كامل للأجهزة.",
    features: [
      "تحليل الاستهلاك الكهربائي",
      "تصميم النظام الشمسي",
      "حساب العائد (ROI)",
      "محاكاة 25 سنة",
      "تدقيق الأجهزة",
    ],
    icon: "☀️",
    image: null,
    badge: "جديد",
    badgeColor: "blue",
    rating: 4.7,
    reviews: 82,
    audience: "أصحاب المنازل والمنشآت",
    compatible: "Excel 2016, 2019, 2021, Microsoft 365",
  },
  {
    id: "farm-livestock-planning",
    name: "أدوات تخطيط وتحليل المزرعة والثروة الحيوانية",
    category: "specialized",
    price: 79,
    originalPrice: null,
    description:
      "أدِر مزرعتك بذكاء. تتبّع القطيع والمحاصيل، احسب احتياجات الأعلاف والري، وراقب ربحية مزرعتك.",
    longDescription:
      "أداة متكاملة لإدارة المزارع والثروة الحيوانية. تتابع قطيع الماشية، تتبع المحاصيل الزراعية، تحسب احتياجات الأعلاف والري، وتراقب أرباح المزرعة الشهرية مع تقويم زراعي متكامل.",
    features: [
      "قطيع الماشية",
      "المحاصيل الزراعية",
      "الأعلاف والري",
      "أرباح المزرعة",
      "التقويم الزراعي",
    ],
    icon: "🌾",
    image: null,
    badge: null,
    badgeColor: null,
    rating: 4.6,
    reviews: 56,
    audience: "أصحاب المزارع والثروة الحيوانية",
    compatible: "Excel 2016, 2019, 2021, Microsoft 365",
  },

  // ─── الفئة 6: الحياة والمناسبات ─────────────────────────────────────
  {
    id: "wedding-budget-planner",
    name: "مخطط ميزانية الزواج والمناسبات",
    category: "life-events",
    price: 49,
    originalPrice: null,
    description:
      "خطط زفافك بذكاء — لا مفاجآت مالية في أسعد أيامك. ميزانية كاملة، قائمة مهام، ومقارنة موردين.",
    longDescription:
      "الزواج أسعد المناسبات — لكن المفاجآت المالية تثقله. هذا المخطط يغطي كل تفصيل: ميزانية الزواج الكاملة، قائمة مهام بالمواعيد، مقارنة موردين، إدارة قائمة المدعوين، وجدول يوم الزفاف.",
    features: [
      "ميزانية الزواج التفصيلية",
      "قائمة المهام مع المواعيد",
      "مقارنة الموردين",
      "إدارة قائمة المدعوين",
      "جدول يوم الزفاف",
    ],
    icon: "💍",
    image: null,
    badge: null,
    badgeColor: null,
    rating: 4.8,
    reviews: 143,
    audience: "المقبلون على الزواج والعائلات",
    compatible: "Excel 2016, 2019, 2021, Microsoft 365",
  },
  {
    id: "hajj-umrah-planner",
    name: "مخطط رحلة الحج والعمرة وميزانية السفر",
    category: "life-events",
    price: 29,
    originalPrice: null,
    description:
      "خطط رحلتك الإيمانية بطمأنينة. نظّم ميزانيتك ومناسكك ومستلزماتك، وادّخر لرحلتك.",
    longDescription:
      "رحلة العمر تستحق التخطيط الكامل. هذا المخطط يشمل ميزانية الرحلة التفصيلية، قائمة المستلزمات الكاملة، جدول المناسك، خطة الادخار، وحاسبة تكلفة رحلة العائلة.",
    features: [
      "ميزانية الرحلة التفصيلية",
      "قائمة المستلزمات الكاملة",
      "جدول المناسك",
      "خطة الادخار للرحلة",
      "حاسبة رحلة العائلة",
    ],
    icon: "🕋",
    image: null,
    badge: null,
    badgeColor: null,
    rating: 4.9,
    reviews: 198,
    audience: "المعتمرون والحجاج وعائلاتهم",
    compatible: "Excel 2016, 2019, 2021, Microsoft 365",
  },
  {
    id: "inheritance-calculator",
    name: "حاسبة الميراث وتقسيم التركة الشرعية",
    category: "life-events",
    price: 29,
    originalPrice: null,
    description:
      "وزّع التركة وفق أحكام الفرائض الإسلامية بدقة ووضوح. حساب صافي التركة، أنصبة الورثة، ودليل فرائض.",
    longDescription:
      "أداة استرشادية لحساب التركة وفق أحكام الفرائض الإسلامية. تحسب صافي التركة، تحدد أنصبة كل وارث، وتوفر دليلاً مرجعياً لأحكام الفرائض. يُنصح باعتماد التقسيم النهائي من مختص.",
    features: [
      "حساب صافي التركة",
      "الورثة وأنصبتهم الشرعية",
      "جدول التقسيم",
      "دليل أحكام الفرائض",
    ],
    icon: "📜",
    image: null,
    badge: null,
    badgeColor: null,
    rating: 4.8,
    reviews: 167,
    audience: "العائلات والمهتمون بأحكام المواريث",
    compatible: "Excel 2016, 2019, 2021, Microsoft 365",
  },
  {
    id: "student-budget-planner",
    name: "مخطط الميزانية الطلابية والمنح الدراسية",
    category: "life-events",
    price: 29,
    originalPrice: null,
    description:
      "للطلاب وأسرهم — خطط مصاريف الدراسة، قارن المنح، وأدِر مكافأتك الجامعية بذكاء.",
    longDescription:
      "الحياة الجامعية تستحق تخطيطاً مالياً جاداً. هذا المخطط يساعد الطلاب وأسرهم على إدارة الميزانية الطلابية، تكلفة الدراسة، مقارنة المنح المتاحة، ميزانية الابتعاث، وخطة ادخار الدراسة.",
    features: [
      "الميزانية الطلابية الشهرية",
      "تكلفة الدراسة التفصيلية",
      "مقارنة المنح الدراسية",
      "ميزانية الابتعاث",
      "خطة ادخار الدراسة",
    ],
    icon: "🎓",
    image: null,
    badge: null,
    badgeColor: null,
    rating: 4.7,
    reviews: 112,
    audience: "الطلاب وأولياء الأمور",
    compatible: "Excel 2016, 2019, 2021, Microsoft 365",
  },
];

// Featured products for homepage (one from each category)
export const featuredProductIds = [
  "personal-budget-planner",
  "loan-bank-comparison",
  "tadawul-stocks-analysis",
  "restaurant-management",
  "ecommerce-analytics",
  "business-docs-bundle",
];

export function getProductById(id) {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(categoryId) {
  return products.filter((p) => p.category === categoryId);
}

export function getBadgeStyle(color) {
  const styles = {
    emerald: "bg-emerald-100 text-emerald-700",
    blue: "bg-blue-100 text-blue-700",
    violet: "bg-violet-100 text-violet-700",
    amber: "bg-amber-100 text-amber-700",
  };
  return styles[color] || "bg-gray-100 text-gray-700";
}
